controllers/user_controller.py
from flask import request, redirect, url_for, Blueprint

from models.user_model import User
from views import user_view
from decorators import login_required

user_bp=Blueprint('user',__name__,url_prefix="/users")

@user_bp.route("/")
@login_required
def index():
    #recupera los registros de la tabla users en forma de objeto
    users=User.get_all()
    return user_view.list(users)

@user_bp.route("/create", methods=['GET','POST'])
@login_required
def create():
    if request.method =='POST':
        name=request.form['name']
        username=request.form['username']
        password=request.form['password']
        rol=request.form['rol']

        user=User(name,username,password,rol)
        user.save()
        return redirect(url_for('user.index'))
    
    return user_view.create()

@user_bp.route("/edit/<int:id>",methods=['GET','POST'])
def edit(id):
    user=User.get_by_id(id)
    if request.method=='POST':
        name=request.form['name']
        username=request.form['username']
        password=request.form['password']
        rol=request.form['rol']
        #actualizar
        user.update(name=name,username=username,password=password,rol=rol)
        return redirect(url_for('user.index'))
    
    return user_view.edit(user)
@user_bp.route("/delete/<int:id>")
def delete(id):
    user=User.get_by_id(id)
    user.delete()
    return redirect(url_for('user.index'))

views/user_view.py
from flask import render_template

def list(users):
    return render_template('users/index.html',users=users)

def create():
    return render_template('users/create.html')

def edit(user):
    return render_template('users/edit.html',user=user)

templates/users/create.html
{% extends 'base.html' %}

{% block title %} USERS | CREATE {% endblock %}

{% block content %}

<h1>Register of user</h1>

<form action="{{ url_for('user.create')}}" method="POST">
    <div class="mb-3">
        <label for="" class="form-label">Name</label>
        <input type="text" class="form-control" name="name" required>

    </div>
    <div class="mb-3">
        <label for="" class="form-label">user</label>
        <input type="text" class="form-control" name="username" required>
        
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Password</label>
        <input type="password" class="form-control" name="password" required>
        
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Rol</label>
        <select name="rol" class="form-select" required>
            <option value="admin">Admin</option>
            <option value="operator">Operator</option>
        </select>
        
    </div>
    <button type="submit" class="btn btn-primary">Register user</button>
</form>

{% endblock %}

templates/users/edit.html
{% extends 'base.html' %}

{% block title %} USERS | EDIT {% endblock %}

{% block content %}

<h1>Update Users</h1>

<form action="{{ url_for('user.edit', id=user.id)}}" method="POST">
    <div class="mb-3">
        <label for="" class="form-label">Name</label>
        <input type="text" class="form-control" name="name" value="{{ user.name}}"required>

    </div>
    <div class="mb-3">
        <label for="" class="form-label">User</label>
        <input type="text" class="form-control" name="username" value="{{ user.username}}" required>
        
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Password</label>
        <input type="password" class="form-control" name="password">
        
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Rol</label>
        <select name="rol" class="form-select" required>
            <option value="admin" {% if user.rol == 'admin' %}selected{% endif %}>Admin</option>
            <option value="operator"  {% if user.rol == 'operator' %}selected{% endif %}>Operator</option>
        </select>
        
    </div>
    <button type="sibmit" class="btn btn-primary">Update user</button>
</form>

{% endblock %}

templates/users/index.html
{% extends 'base.html' %}

{% block title %} USERS {% endblock %}

{% block content %}

<h1>Lista de users</h1>

<a href="{{ url_for('user.create') }}" class="btn btn-success mb-3">Nuevo</a>

<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Username</th>
        <th>Rol</th>
        <th></th>
        <th></th>
    </tr>
    {% for item in users %}
    <tr>
        <td>{{item.id}}</td>
        <td>{{item.name}}</td>
        <td>{{item.username}}</td>
        <td>{{item.rol}}</td>
        <td>
            <a href="{{ url_for('user.edit',id=item.id)}}" class="btn btn-warning">Edit</a>

        </td>
        <td>
            <a href="{{ url_for('user.delete',id=item.id)}}" class="btn btn-danger">Delete</a>
        </td>
    </tr>
    {% endfor %}
</table>


{% endblock %}