controllers/client_controller.py
from flask import request, redirect, url_for, Blueprint

from models.client_model import Client
from views import client_view
from decorators import login_required

client_bp=Blueprint('client',__name__,url_prefix="/clients")

@client_bp.route("/")
@login_required
def index():
    #recupera los registros de la tabla clients en forma de objeto
    clients=Client.get_all()
    return client_view.list(clients)

@client_bp.route("/create", methods=['GET','POST'])
def create():
    if request.method =='POST':
        name=request.form['name']
        email=request.form['email']
        address=request.form['address']
        phone=request.form['phone']

        client=Client(name,email,address,phone)
        client.save()
        return redirect(url_for('client.index'))
    
    return client_view.create()

@client_bp.route("/edit/<int:id>",methods=['GET','POST'])
def edit(id):
    client=Client.get_by_id(id)
    if request.method=='POST':
        name=request.form['name']
        email=request.form['email']
        address=request.form['address']
        phone=request.form['phone']
        #actualizar
        client.update(name=name,email=email,address=address, phone=phone)
        return redirect(url_for('client.index'))
    
    return client_view.edit(client)
@client_bp.route("/delete/<int:id>")
def delete(id):
    client=Client.get_by_id(id)
    client.delete()
    return redirect(url_for('client.index'))

views/client_view.py
from flask import render_template

def list(clients):
    return render_template('clients/index.html',clients=clients)

def create():
    return render_template('clients/create.html')

def edit(client):
    return render_template('clients/edit.html',client=client)

templates/clients/create.html
{% extends 'base.html' %}

{% block title %} CLIENTS | CREATE {% endblock %}

{% block content %}

<h1>Register of client</h1>

<form action="{{ url_for('client.create')}}" method="POST">
    <div class="mb-3">
        <label for="" class="form-label">Name</label>
        <input type="text" class="form-control" name="name" required>

    </div>
    <div class="mb-3">
        <label for="" class="form-label">email</label>
        <input type="email" class="form-control" name="email" required>
        
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Address</label>
        <input type="text" class="form-control" name="address" required>
        
    </div>
    <div class="mb-3">
        <label for="" class="form-label">phone</label>
        <input type="number" class="form-control" name="phone" required>
        
    </div>

    <button type="sibmit" class="btn btn-primary">Register of client</button>
</form>

{% endblock %}

templates/clients/edit.html
{% extends 'base.html' %}

{% block title %} CLIENTS | CREATE {% endblock %}

{% block content %}

<h1>Update client</h1>

<form action="{{ url_for('client.edit',id=client.id)}}" method="POST">
    <div class="mb-3">
        <label for="" class="form-label">name</label>
        <input type="text" class="form-control" name="name" value="{{ client.name}}" required>

    </div>
    <div class="mb-3">
        <label for="" class="form-label">email</label>
        <input type="email" class="form-control" name="email" value="{{ client.email}}" required>
        
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Address</label>
        <input type="text" class="form-control" name="address" value="{{ client.address}}" required>
        
    </div>
    <div class="mb-3">
        <label for="" class="form-label">phone</label>
        <input type="number" class="form-control" name="phone" value="{{ client.phone}}" required>
        
    </div>

    <button type="sibmit" class="btn btn-primary">update client</button>
</form>

{% endblock %}

templates/clients/index.html
{% extends 'base.html' %}

{% block title %} CLIENTS {% endblock %}

{% block content %}

<h1>List of clients</h1>

<a href="{{ url_for('client.create') }}" class="btn btn-success mb-3">Nuevo</a>

<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>email</th>
        <th>address</th>
        <th>phone</th>
        <th></th>
        <th></th>
    </tr>
    {% for item in clients %}
    <tr>
        <td>{{item.id}}</td>
        <td>{{item.name}}</td>
        <td>{{item.email}}</td>
        <td>{{item.address}}</td>
        <td>{{item.phone}}</td>
        <td>
            <a href="{{ url_for('client.edit',id=item.id)}}" class="btn btn-warning">Edit</a>

        </td>
        <td>
            <a href="{{ url_for('client.delete',id=item.id)}}" class="btn btn-danger">Delete</a>
        </td>
    </tr>
    {% endfor %}
</table>


{% endblock %}